steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t $$USERNAME/deit:${_ROS_VERSION}-${_TAG} . --build-arg ROS_VERSION=${_ROS_VERSION} --build-arg MODEL_VERSION=${_MODEL_VERSION} --build-arg ORGANIZATION=${_ORGANIZATION}']
    secretEnv: ['USERNAME']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push $$USERNAME/deit:${_ROS_VERSION}-${_TAG}']
    secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
    - versionName: projects/shade-prod/secrets/DOCKER_PASSWORD_SECRET_NAME/versions/1
      env: 'PASSWORD'
    - versionName: projects/shade-prod/secrets/DOCKER_USERNAME_SECRET_NAME/versions/1
      env: 'USERNAME'
